### ISSUE TITLE
Help to get started

### ISSUE THREAD

**Issue by magnus-staberg** [asfaltboy/SublimeTestPlier#13]
Looks like an awesome plugin to start using py.test in Sublime's build system.
However I'm having problem getting it started.
This confuses me:

> The simplest usage is simply running the build system; ctrl+shift+b (super+shift+b on OSX) and select **test_plier - Python Tests** from the build system selection drop-down, after using it once you may hit ctrl+b (super+b on OSX) to run the build system again. Alternatively, select **test_plier - Python Tests (external)** to run the test in an external terminal window.

Because when I installed this plugin I only see test_plier as a new option in "Tools" ->  "Build System".
If I choose that option and press cmd+b I get "No build system" in Sublime's bar at the bottom of the window. Tapping cmd+shift+b and placing the cursor on a test I get same result.

In my project file I added:
```
"build_systems":` [
        {
            "name": "Test Plier",
            "cmd": ["pytest", "tests/browser/app_name/{filename}"],
        }
    ]
```
If I choose "Test Plier as Build system it says
ERROR: file not found: 

> tests/browser/app_name/{filename}

which makes sense.

Can you please specify how to setup so that I simply can run a test that my cursor is placed on?
I use latest released Sublime Text 3.
Thanks in advance :)

**Comment by asfaltboy** [comment]
Hi @magnus-staberg ! Thank you for your interest in the plugin.

1. In regards to the included (default) build file:

    May I ask, have you installed the release from package-control? If so, it may be slightly out of date; the build file is malfunctioning in last release. I'll be releasing 1.3.0 shortly, it's long due. You should normally see an update within a few hours.

    Alternatively, if you are comfortable with [installing SublimeTestPlier by cloning the plugin source from git][1], you may checkout the "develop" branch directly, to use the latest version.

2. In regards to setting up a custom build system:

    Your snippet above needs to specify the "target" property like so:


    ```python
"build_systems":` [
        {
            "name": "Test Plier",
            // cmd is not necessery as [pytest, selector] is the default command
            // "cmd": ["pytest", "tests/browser/app_name/{filename}"],
            "target": "run_python_tests"
        }
]
    ```

I have also updated [the readme][2] to reflect that target is required, as well as noting the default "cmd".

[1]: https://packagecontrol.io/docs/customizing_packages
[2]: https://github.com/asfaltboy/SublimeTestPlier#configuration

**Comment by magnus-staberg** [comment]
Thanks for your quick reply.
1)
Yes, I've installed it using package-control. Sorry, I should have mentioned that.
I'll wait for the 1.3.0. Looking forward to it and will write here about how it goes!
2)
Thanks for elucidating cmd and target attributes.

**Comment by asfaltboy** [comment]
@magnus-staberg I'm pleased to update that [version 1.3 is available on package control](https://packagecontrol.io/packages/Test%20Plier).

I made a quick test run and it works as expected. Please update here if you have any other issues.

**Comment by StabbarN** [comment]
Awesome, now it works flawlessly :)
