### ISSUE TITLE
Tests fail to run due to improper relative imports

### ISSUE THREAD

**Issue by asfaltboy** [asfaltboy/SublimeTestPlier#3]
We should at least skip / comment out those failing tests until we can resolve this.

**Comment by yprez** [comment]
This happens because Python doesn't know how to handle the dashes in the directory name (Sublime-Test-Plier), so it doesn't see it as a package.

Renaming the dir to "SublimeTestPlier" fixes it locally. I think renaming the Github project will fix the the travis build.

**Comment by asfaltboy** [comment]
You, my good sir, are a _gentleman_! Check the updated badge for the green delight !! :green_heart:
